version: "3.9"

services:
  # standalone
  # prerequisite for: dbsync, wallet-api, ogmios, submit-api
  apex-relay:
    image: ghcr.io/intersectmbo/cardano-node:8.7.3
    environment:
      - CARDANO_BLOCK_PRODUCER=false
      - CARDANO_CONFIG=/config/configuration.yaml
      - CARDANO_TOPOLOGY=/config/topology.json
      - CARDANO_DATABASE_PATH=/data/db
      - CARDANO_SOCKET_PATH=/ipc/node.socket
      - CARDANO_LOG_DIR=/data/node.log
      - CARDANO_BIND_ADDR=0.0.0.0
      - CARDANO_PORT=7532
    command:
      - run
    volumes:
      - ../test-data/node-ipc:/ipc
      - node-db:/data/db
      - ./genesis:/genesis
      - ./config/relay:/config
    restart: on-failure
    healthcheck:
      # Ping the EKG port to see if it responds.
      # Assuming if EKG isn't up then the rest of cardano-node isn't either.
      test: ["CMD-SHELL", "curl -f 127.0.0.1:12788 || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  # requires: apex-relay
  wallet-api:
    image: cardanofoundation/cardano-wallet:2023.12.18
    volumes:
      - ../test-data/node-ipc:/ipc
      - wallet-api-data:/wallet-db
      - ./genesis:/genesis
    ports:
      - 8090:8090
    entrypoint: []
    command: bash -c "
        ([[ $$NETWORK == \"mainnet\" ]] && $$CMD --mainnet) ||
        ($$CMD --testnet /genesis/byron/genesis.json)
      "
    environment:
      CMD: "cardano-wallet serve --node-socket /ipc/node.socket --database /wallet-db --listen-address 0.0.0.0"
      NETWORK:
    depends_on:
      apex-relay:
        condition: service_healthy
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  # requires: wallet-api
  icarus:
    image: piotrstachyra/icarus:v2023-04-14
    network_mode: "host"
    restart: on-failure
    depends_on:
      wallet-api:
        condition: service_started

  # requires: apex-relay
  ogmios:
    image: cardanosolutions/ogmios:v6.1.0
    restart: on-failure
    command: [
      "--host", "0.0.0.0",
      "--node-socket", "/ipc/node.socket",
      "--node-config", "/config/configuration.yaml"
    ]
    volumes:
      - ../test-data/node-ipc:/ipc
      - ./genesis:/genesis
      - ./config/ogmios:/config
    ports:
      - ${OGMIOS_PORT:-1337}:1337
    depends_on:
      apex-relay:
        condition: service_healthy


volumes:
  # apex-relay, wallet-api, ogmios, submit-api
  #node-ipc:
  # apex-relay
  node-db:
  # wallet-api
  wallet-api-data:
